<a href="https://colab.research.google.com/github/Vanshbhattok/AIML-Experiment-8/blob/main/Experiment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Experiment - 8 PCA Part

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#Example Dataset: A sample dataset with 3 features.

X = np.array ([[1.0, 3.4],
               [0.5, 0.7],
               [1.2, 1.9],
               [2.1, 2.8],
               [8.3, 7.1],
               [7.2, 1.1],
               [2.2, 1.1],
               [1.0, 10.2],
               [4.2, 1.8],
               [4.3, 4.1],
               [0.2, 0.3]])


#Standardize the data

#Compute the mean and standard deviation of each feature

X_mean = np.mean(X, axis=0)
X_std = (X- X_mean)/ np.std(X, axis=0)

print("Standorized Dataset: ")
print(X_std)


#Compute the covariance matrix
cov_matrix = np.cov(X_std.T)
print("Covariance Matrix:")
print(cov_matrix)


#Compute eigenvalues and eigenvectors from the covarience matrix

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)



sorted_indices = np.argsort(np.linalg.eigvals(cov_matrix))[::-1]
eigenvalues_sorted = eigenvalues[sorted_indices]
eigenvectors_sorted = eigenvectors[:, sorted_indices]

print("Sorted Eigenvalues: ")
print(eigenvalues_sorted)
print("Sorted Eigenvectors: ")
print(eigenvectors_sorted)












Standorized Dataset: 
[[-0.73524292  0.09100976]
 [-0.9259899  -0.84105572]
 [-0.65894413 -0.4268044 ]
 [-0.31559956 -0.1161159 ]
 [ 2.04966304  1.36828468]
 [ 1.63001968 -0.70297195]
 [-0.27745016 -0.70297195]
 [-0.73524292  2.43843393]
 [ 0.48553778 -0.46132534]
 [ 0.52368717  0.33265637]
 [-1.04043809 -0.97913949]]
Covariance Matrix:
[[1.1       0.2059595]
 [0.2059595 1.1      ]]
Eigenvalues:
[1.3059595 0.8940405]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Sorted Eigenvalues: 
[1.3059595 0.8940405]
Sorted Eigenvectors: 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
